### ISSUE TITLE
Node Name Labels

### ISSUE THREAD

**Issue by BeyondAman** [Luganodes/hypermon#1]
Expose name based labels as well that can show the name of the node / validator similar to address label

**Comment by Frixoe** [comment]
That is a conscious implementation decision and we have decided not to add that on purpose as validator addresses are immutable and serve the purpose of names for all usecases. If you can come up with a usecase that needs validator names, feel free to open a PR :)

**Comment by BeyondAman** [comment]
I understand and agree with your point that validator addresses are immutable and serve as identifiers. However, for a monitoring tool, it might make more sense to have an additional layer, similar to IP addresses and DNS. Without name association, listing multiple addresses in the dashboard requires extra steps, such as navigating to an explorer for details. With names, this process could be simplified and streamlined, improving usability.
